"""added last_sign_in users

Revision ID: 4ae7e18a8ad2
Revises: 4be8955dd5ee
Create Date: 2026-10-06 00:22:46.183705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4ae7e18a8ad2'
down_revision: Union[str, Sequence[str], None] = '4be8955dd5ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column(
            'last_sign_in',
            sqlmodel.sql.sqltypes.UTCDateTime(),
            nullable=False,
            server_default=sa.func.now(),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_sign_in')
    # ### end Alembic commands ###
