"""removed refresh_session revoked_at

Revision ID: 4be8955dd5ee
Revises: 6d6e3c931e56
Create Date: 2026-10-01 20:00:36.137461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4be8955dd5ee'
down_revision: Union[str, Sequence[str], None] = '6d6e3c931e56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_refresh_session_expires_at'), 'refresh_session', ['expires_at'], unique=False)
    op.drop_column('refresh_session', 'revoked')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_session', sa.Column('revoked', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_refresh_session_expires_at'), table_name='refresh_session')
    # ### end Alembic commands ###
