"""add contact_detail and defaults

Revision ID: 63e1cfb8eb5b
Revises: 7a61451e9c9a
Create Date: 2026-10-10 03:38:37.646007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '63e1cfb8eb5b'
down_revision: Union[str, Sequence[str], None] = '7a61451e9c9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('computer_name', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False))
    op.drop_column('devices', 'model')
    op.drop_column('devices', 'brand')
    op.add_column('repair_requests', sa.Column('contact_detail', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repair_requests', 'contact_detail')
    op.add_column('devices', sa.Column('brand', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('devices', sa.Column('model', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    op.drop_column('devices', 'computer_name')
    # ### end Alembic commands ###
