"""added refresh_sessions

Revision ID: 6d6e3c931e56
Revises: bab9aecd2c9b
Create Date: 2026-09-28 23:28:42.147372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6d6e3c931e56'
down_revision: Union[str, Sequence[str], None] = 'bab9aecd2c9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_session_token_hash'), 'refresh_session', ['token_hash'], unique=False)
    op.create_index(op.f('ix_refresh_session_user_id'), 'refresh_session', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_session_user_id'), table_name='refresh_session')
    op.drop_index(op.f('ix_refresh_session_token_hash'), table_name='refresh_session')
    op.drop_table('refresh_session')
    # ### end Alembic commands ###
