"""change conversation and message table 2

Revision ID: 7a61451e9c9a
Revises: 818b282ec463
Create Date: 2026-10-09 15:25:17.559563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7a61451e9c9a'
down_revision: Union[str, Sequence[str], None] = '818b282ec463'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('repair_request_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_conversations_customer_id'), table_name='conversations')
    op.create_index(op.f('ix_conversations_customer_id'), 'conversations', ['customer_id'], unique=False)
    op.create_index(op.f('ix_conversations_repair_request_id'), 'conversations', ['repair_request_id'], unique=True)
    op.create_foreign_key(None, 'conversations', 'repair_requests', ['repair_request_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_index(op.f('ix_conversations_repair_request_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_customer_id'), table_name='conversations')
    op.create_index(op.f('ix_conversations_customer_id'), 'conversations', ['customer_id'], unique=True)
    op.drop_column('conversations', 'repair_request_id')
    # ### end Alembic commands ###
