"""add parts columns and created_at defaults

Revision ID: 7aae560d788a
Revises: cdc817baee28
Create Date: 2026-10-10 11:32:47.967493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7aae560d788a'
down_revision: Union[str, Sequence[str], None] = 'cdc817baee28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parts', sa.Column('reorder_threshold', sa.Integer(), nullable=False, server_default='5'))
    op.add_column('parts', sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'))
    op.create_index(op.f('ix_parts_category'), 'parts', ['category'], unique=False)
    op.create_index(op.f('ix_parts_is_active'), 'parts', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parts_is_active'), table_name='parts')
    op.drop_index(op.f('ix_parts_category'), table_name='parts')
    op.drop_column('parts', 'is_active')
    op.drop_column('parts', 'reorder_threshold')
    # ### end Alembic commands ###
