"""change conversation and message table

Revision ID: 818b282ec463
Revises: 4ae7e18a8ad2
Create Date: 2026-10-08 11:59:10.232080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '818b282ec463'
down_revision: Union[str, Sequence[str], None] = '4ae7e18a8ad2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('last_message_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False))
    op.create_index(op.f('ix_conversations_last_message_at'), 'conversations', ['last_message_at'], unique=False)
    op.drop_column('conversations', 'updated_at')
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.add_column('conversations', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_conversations_last_message_at'), table_name='conversations')
    op.drop_column('conversations', 'last_message_at')
    # ### end Alembic commands ###
