"""add supplier to parts

Revision ID: 8cc9443b901d
Revises: 7aae560d788a
Create Date: 2026-10-10 12:41:43.143401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8cc9443b901d'
down_revision: Union[str, Sequence[str], None] = '7aae560d788a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parts', sa.Column('supplier', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parts', 'supplier')
    # ### end Alembic commands ###
